### ISSUE TITLE
java.lang.IllegalStateException: Stacktrace-decoroutinator runtime can not be loaded because BaseContinuationImpl was already loaded.

### ISSUE THREAD

**Issue by kenny-statsig** [Anamorphosee/stacktrace-decoroutinator#23]
I am calling `DecoroutinatorRuntime.load()` at the top of my app's onCreate but it seems to be causing the app to crash
I've attached a screenshot of the full stack trace.

![Screenshot 2023-06-22 at 1 50 43 PM](https://github.com/Anamorphosee/stacktrace-decoroutinator/assets/111380336/4c106b3f-9d6d-4d08-9fb6-bfdd601f1724)

**Comment by Anamorphosee** [comment]
@kenny-statsig It seems you add calling `DecoroutinatorRuntime.load()` to the MainActivity's `onCreate()` method  instead of the Application's one.
Please see the correct example from the Android tests.
https://github.com/Anamorphosee/stacktrace-decoroutinator/blob/master/stacktrace-decoroutinator-android/src/androidTest/AndroidManifest.xml
https://github.com/Anamorphosee/stacktrace-decoroutinator/blob/master/stacktrace-decoroutinator-android/src/androidTest/kotlin/utils-test.kt#L31

**Comment by MarcLFJ** [comment]
I encountered the same issue. I had the .load() setup correctly in our Application class and still ran into this issue.
Tried moving it to the `init {...}`, but same result.
We are using dependency injection (Hilt), and some of the injected classes has coroutines in their `init()`, which might be the issue? 🤔 
I did not find a workaround

**Comment by jhollowayj** [comment]
I first tried using the suggested `onCreate`, but got that same "BaseContinuationImpl was already loaded" error.
I switched to use the `init{}` block in my Application file and things started working!

I'd bet that having coroutines in your hilt stuff is what's causing the BaseContinuationImpl to be loaded before you'd like.  I don't know a solution for you, but wanted to say that your `init` trick is greatly appreciated!

**Comment by saket** [comment]
That did the trick, thank you!

**Comment by Anamorphosee** [comment]
Just released SD version 2.4.0 with a big rework for Android. From now on SD for Android requires only [the Gradle plugin](https://github.com/Anamorphosee/stacktrace-decoroutinator?tab=readme-ov-file#android) and no other dependencies or method calls are required.
